name: Waka Readme

on:
  # for manual workflow trigger
  workflow_dispatch:
  schedule:
    # runs at 12 AM UTC
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      # This action fetches and updates WakaTime stats in your README
      - uses: athul/waka-readme@master # do NOT replace with anything else
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }} # optional if on profile readme
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }} # required
          ### meta
          API_BASE_URL: https://wakatime.com/api # optional
          REPOSITORY: YOUR_GITHUB_USERNAME/YOUR_REPOSITORY_NAME # optional
          ### content
          SHOW_TITLE: true # optional, displays the title "WakaTime Stats"
          SECTION_NAME: waka # optional, name of the section in the README
          BLOCKS: -> # optional
          CODE_LANG: rust # optional
          TIME_RANGE: all_time # optional, can use last_7_days or last_30_days
          LANG_COUNT: 10 # optional, shows 10 languages
          SHOW_TIME: true # optional, shows time spent
          SHOW_TOTAL: true # optional, shows total coding activity
          SHOW_MASKED_TIME: false # optional
          STOP_AT_OTHER: true # optional
          IGNORED_LANGUAGES: YAML JSON TOML # optional, hides these languages from the display
          ### commit
          COMMIT_MESSAGE: Updated waka-readme graph with new metrics # optional
          TARGET_BRANCH: master # optional, default branch to commit to
          TARGET_PATH: README.md # optional, where the WakaTime stats are inserted
          COMMITTER_NAME: GitHubActionBot # optional, name of the committer
          COMMITTER_EMAIL: action-bot@github.com # optional, email of the committer
          AUTHOR_NAME: YOUR_NAME # optional, your name as the author
          AUTHOR_EMAIL: YOUR@EMAIL.com # optional, your email address
