name: Waka Readme

on:
  # Manual workflow trigger
  workflow_dispatch:
  schedule:
    # Runs daily at 12 AM UTC
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      # Fetches and updates WakaTime stats in your README
      - uses: athul/waka-readme@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }} # Optional, can be omitted if default token is used
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }} # Required
          ### meta
          API_BASE_URL: https://wakatime.com/api # Optional
          REPOSITORY: roger-ui/roger-ui # Optional
          ### content
          SHOW_TITLE: true # Displays "WakaTime Stats" title
          SECTION_NAME: waka # Defines section in README
          BLOCKS: -> # Optional
          CODE_LANG: markdown # Highlight markdown as code language
          TIME_RANGE: last_7_days # Time range to display
          LANG_COUNT: 10 # Shows top 10 languages
          SHOW_TIME: true # Displays time spent
          SHOW_TOTAL: true # Shows total coding time
          SHOW_MASKED_TIME: false # Don't mask time
          STOP_AT_OTHER: true # Stop display at 'Other' category
          IGNORED_LANGUAGES: YAML JSON TOML # Ignore these languages
          ### commit
          COMMIT_MESSAGE: Updated waka-readme graph with new metrics # Commit message
          TARGET_BRANCH: main # Default branch to commit to
          TARGET_PATH: README.md # Where the WakaTime stats are inserted
          COMMITTER_NAME: GitHubActionBot # Committer name
          COMMITTER_EMAIL: action-bot@github.com # Committer email
          AUTHOR_NAME: Roger Vargas # Your name
          AUTHOR_EMAIL: roger3943@gmail.com # Your email
