name: Waka Readme

on:
  schedule:
    # Runs every 4 hours from Monday (1) to Friday (5)
    - cron: '0 */4 * * 1-5'
  workflow_dispatch:

jobs:
  update-readme:
    name: Waka with metrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }} 
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }} 
          API_BASE_URL: https://wakatime.com/api 
          REPOSITORY: roger-ui/roger-ui 
          SHOW_TITLE: true 
          SECTION_NAME: waka 
          BLOCKS: -> 
          CODE_LANG: python 
          TIME_RANGE: all_time 
          LANG_COUNT: 10 
          SHOW_TIME: true 
          SHOW_TOTAL: true 
          SHOW_MASKED_TIME: false 
          STOP_AT_OTHER: false 
          IGNORED_LANGUAGES: Other YAML JSON TOML 
          COMMIT_MESSAGE: Updated waka-readme graph with new metrics 
          TARGET_BRANCH: main 
          TARGET_PATH: README.md 
          COMMITTER_NAME: GitHubActionBot 
          COMMITTER_EMAIL: action-bot@github.com 
          AUTHOR_NAME: Roger Vargas 
          AUTHOR_EMAIL: roger3943@gmail.com 
